version: '3.8'

services:
  app:
    build:
      context: ./docker
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel

volumes:
  mysql_data:
